[colors]
"diff removed token" = { bg = "#221111", underline = false }
"diff added token" = { bg = "#002200", underline = false }

[revset-aliases]
# Set all remote bookmarks (commits pushed to remote branches) to be immutable.
'immutable_heads()' = "builtin_immutable_heads() | remote_bookmarks()"

[template-aliases]
# Show author timestamps by default, since that's what Git does.
'commit_timestamp(commit)' = 'commit.author().timestamp()'
'format_short_id(id)' = 'id.shortest(5)'
'format_short_signature(signature)' = 'signature.name()'

[ui]
default-command = "log"
merge-editor = ":builtin"
